version: '3.8'

services:
  qwen3-grpc-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32688:32688"
    environment:
      - GRPC_PORT=32688
      - CUDA_VISIBLE_DEVICES=0  # 指定使用哪个GPU
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./Models:/app/Models:ro  # 只读挂载模型文件
    restart: unless-stopped
    runtime: nvidia  # 使用NVIDIA Docker运行时
    deploy:
      resources:
        limits:
          memory: 16G  # GPU环境下增加内存限制
        reservations:
          memory: 8G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; channel = grpc.insecure_channel('localhost:32688'); channel.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # GPU模型加载需要更多时间
    networks:
      - qwen3-network

networks:
  qwen3-network:
    driver: bridge
